categories = {
    "animal": [
        "A zebra with stripes turning into piano keys, Dixit, musical, surreal",
        "A dolphin leaping through a hoop of rainbows, Dixit, fantasy, vibrant",
        "A snail carrying a tiny greenhouse on its shell, Dixit, dreamy, botanical",
        "A kangaroo with a pocket full of stars, Dixit, whimsical, night",
        "A butterfly with wings made of stained glass, Dixit, artistic, colorful",
        "A fox hiding in a field of origami flowers, Dixit, creative, paper art",
        "A penguin ice-skating on a frozen lake of mirrors, Dixit, surreal, reflective",
        "A chameleon blending into a patchwork quilt, Dixit, cozy, textile",
        "A giraffe eating leaves from a floating tree, Dixit, magical, floating islands",
        "A bear fishing in a river of glowing lanterns, Dixit, fantasy, light",
        "A squirrel with a tail made of autumn leaves, Dixit, seasonal, whimsical",
        "A rabbit painting eggs in a field of tulips, Dixit, spring, artistic",
        "A wolf howling at a sky full of balloons, Dixit, surreal, playful",
        "A cat sleeping on a crescent moon hammock, Dixit, dreamy, night",
        "A dog with a collar of tiny bells, Dixit, festive, cheerful",
        "A mouse reading a map under a giant mushroom, Dixit, adventure, forest",
        "A peacock with feathers that look like stained glass windows, Dixit, artistic, vibrant",
        "A horse galloping on a rainbow bridge, Dixit, fantasy, colorful",
        "A turtle with a city on its shell, Dixit, urban, surreal",
        "A frog playing chess with a dragonfly, Dixit, whimsical, pond",
        "A fox and a rabbit sharing an umbrella in the rain, Dixit, friendship, cozy",
        "A lion with a mane of sunflowers, Dixit, summer, bright",
        "A monkey swinging from a chandelier, Dixit, playful, indoor",
        "A hedgehog rolling through a field of dandelions, Dixit, spring, light",
        "A flamingo standing in a pool of stars, Dixit, night, magical",
        "A raccoon baking a pie in a forest kitchen, Dixit, culinary, woodland",
        "A swan gliding across a lake of clouds, Dixit, dreamy, sky",
        "A goat climbing a spiral staircase made of books, Dixit, surreal, knowledge",
        "A mouse sailing a walnut shell boat, Dixit, adventure, tiny",
        "A bear wearing a scarf made of autumn leaves, Dixit, cozy, seasonal"
    ],
    "book": [
        "A book with pages that unfold into a paper city, Dixit, origami, urban",
        "A bookshelf shaped like a spiral galaxy, Dixit, cosmic, dreamy",
        "A child riding a flying book over a mountain range, Dixit, adventure, landscape",
        "A library with ladders reaching into the clouds, Dixit, whimsical, sky",
        "A book whose words float off the page as fireflies, Dixit, magical, night",
        "A stack of books forming a bridge over a river, Dixit, fantasy, crossing",
        "A book with a waterfall of letters pouring out, Dixit, surreal, typography",
        "A book with a garden growing between its pages, Dixit, botanical, lush",
        "A book with a window showing a different world, Dixit, portal, alternate reality",
        "A book with a cover that changes colors like a chameleon, Dixit, artistic, color shift",
        "A book with a lock and a tiny golden key, Dixit, mysterious, treasure",
        "A bookshelf shaped like a tree, Dixit, nature, organic",
        "A book with a pop-up castle inside, Dixit, fantasy, interactive",
        "A book with a river flowing through its pages, Dixit, water, movement",
        "A book with a cover made of stained glass, Dixit, artistic, glowing",
        "A book with a staircase leading to the stars, Dixit, dreamy, cosmic",
        "A book with a mirror inside reflecting a magical forest, Dixit, surreal, nature",
        "A book with a night sky painted on its pages, Dixit, dreamy, stars",
        "A book with a door opening to a secret garden, Dixit, hidden, botanical",
        "A book with a rainbow arching from its spine, Dixit, colorful, whimsical",
        "A book with a tiny boat sailing on an ocean of ink, Dixit, adventure, creative",
        "A book with a castle rising from its pages, Dixit, fantasy, majestic",
        "A book with musical notes floating out, Dixit, artistic, sound",
        "A book with a fox reading under a lantern, Dixit, cozy, animal",
        "A book with a cover made of velvet and gold, Dixit, luxurious, tactile",
        "A book with a garden blooming from its center, Dixit, lush, vibrant",
        "A book with a staircase winding around its spine, Dixit, surreal, journey",
        "A book with a glowing sun and moon on each page, Dixit, celestial, duality",
        "A book with a river of stars flowing through, Dixit, cosmic, magical",
        "A book with a door on its cover, opening to a magical world, Dixit, portal, fantasy"
    ],
    "computer": [
        "A computer screen displaying a portal to a jungle, Dixit, adventure, nature",
        "A keyboard with keys blooming into flowers, Dixit, botanical, spring",
        "A mouse with a tail made of glowing fiber optics, Dixit, futuristic, neon",
        "A laptop floating above a city at night, Dixit, urban, lights",
        "A monitor showing a waterfall of code, Dixit, surreal, digital",
        "A computer tower with vines wrapping around it, Dixit, nature, overgrown",
        "A robot painting a digital sunset, Dixit, creative, art",
        "A computer mouse swimming in a cup of coffee, Dixit, whimsical, morning",
        "A screen displaying a map of imaginary lands, Dixit, fantasy, cartography",
        "A keyboard with keys turning into tiny birds, Dixit, transformation, flight",
        "A monitor with a spiral staircase inside, Dixit, surreal, architecture",
        "A computer with a garden blooming from its center, Dixit, botanical, lush",
        "A laptop with a garden growing from the keyboard, Dixit, nature, creative",
        "A computer mouse with a comet tail, Dixit, cosmic, speed",
        "A computer surrounded by floating islands, Dixit, fantasy, imaginative",
        "A computer tower with a door to a magical world, Dixit, portal, fantasy",
        "A monitor with a miniature city inside, Dixit, urban, tiny",
        "A keyboard with keys turning into musical notes, Dixit, artistic, sound",
        "A computer surrounded by a night sky full of stars, Dixit, dreamy, cosmic",
        "A screen displaying a surreal clock, Dixit, time, paradox",
        "A computer with a glowing sun and moon on the screen, Dixit, celestial, duality",
        "A keyboard with keys turning into ribbons, Dixit, whimsical, transformation",
        "A computer with a cover made of stained glass, Dixit, artistic, glowing",
        "A laptop floating on a cloud, keys turning into birds, Dixit, dreamy, sky",
        "A computer mouse painting a rainbow on the screen, Dixit, creative, color",
        "A computer tower glowing in the dark, Dixit, mysterious, light",
        "A computer surrounded by floating books and papers, Dixit, academic, whimsical",
        "A mouse with butterfly wings, Dixit, fantasy, transformation",
        "A computer with a river of code flowing out, Dixit, surreal, movement",
        "A monitor with a tree growing from it, Dixit, nature, growth"
    ],
    "dark": [
        "A moonlit alley with glowing puddles, Dixit, mysterious, night",
        "A shadowy figure holding a lantern of stars, Dixit, fantasy, illumination",
        "A forest where the trees cast rainbow shadows, Dixit, surreal, color",
        "A castle with windows glowing in the fog, Dixit, dreamy, mist",
        "A black cat with eyes like tiny galaxies, Dixit, cosmic, animal",
        "A night sky with clouds shaped like mythical beasts, Dixit, fantasy, sky",
        "A bridge disappearing into the darkness, Dixit, mysterious, journey",
        "A lantern floating on a river of ink, Dixit, poetic, water",
        "A silhouette standing under a rain of glowing petals, Dixit, surreal, floral",
        "A clock tower casting a shadow that tells a different time, Dixit, time, paradox",
        "A dark forest with glowing mushrooms, Dixit, magical, nature",
        "A shadowy figure walking on a path of light, Dixit, contrast, hope",
        "A castle surrounded by swirling shadows, Dixit, fantasy, mysterious",
        "A tree with branches made of shadows, Dixit, artistic, surreal",
        "A night sky filled with surreal, dark clouds, Dixit, dreamy, atmospheric",
        "A lantern illuminating a dark, surreal alley, Dixit, dreamy, city",
        "A river of darkness flowing through a surreal landscape, Dixit, whimsical, water",
        "A figure holding a glowing orb in the dark, Dixit, magical, light",
        "A dark alley with floating lanterns, Dixit, artistic, urban",
        "A tree with leaves made of darkness, Dixit, fantasy, surreal",
        "A night sky with swirling, dark patterns, Dixit, whimsical, sky",
        "A figure standing under a glowing moon, Dixit, dreamy, night",
        "A surreal landscape with dark, twisted trees, Dixit, artistic, forest",
        "A castle surrounded by a sea of darkness, Dixit, fantasy, isolation",
        "A dark forest with glowing fireflies, Dixit, whimsical, insects",
        "A night sky filled with surreal, dark stars, Dixit, dreamy, cosmic",
        "A shadowy figure holding a lantern, Dixit, artistic, mysterious",
        "A surreal landscape with a river of shadows, Dixit, fantasy, water",
        "A dark castle with glowing windows, Dixit, whimsical, architecture",
        "A moon eclipsed by swirling clouds, Dixit, surreal, night"
    ],
    "fire": [
        "A phoenix soaring above a burning forest, Dixit, mythical, rebirth",
        "A lantern floating on a river of lava, Dixit, poetic, surreal",
        "A dragon curled around a candle, flame glowing, Dixit, fantasy, magical",
        "A fireplace with flames forming musical instruments, Dixit, artistic, whimsical",
        "A fox leaping through a ring of fire, Dixit, dynamic, animal",
        "A campfire with flames shaped like dancing people, Dixit, lively, night",
        "A tree with branches made of glowing embers, Dixit, nature, surreal",
        "A candle with a flame that turns into a bird, Dixit, transformation, dreamy",
        "A bonfire surrounded by floating lanterns, Dixit, festival, night",
        "A firefly glowing in a glass jar, surrounded by sparks, Dixit, magical, insect",
        "A castle with towers made of fire, Dixit, fantasy, architecture",
        "A river of fire flowing through a city, Dixit, urban, surreal",
        "A dragon breathing fire into a starry sky, Dixit, cosmic, mythical",
        "A candle melting into a pool of gold, Dixit, luxury, surreal",
        "A fireplace with flames forming a spiral staircase, Dixit, dreamy, home",
        "A fox with a tail of blue fire, Dixit, unusual, animal",
        "A lantern with a flame shaped like a heart, Dixit, romantic, night",
        "A treehouse burning with gentle magical fire, Dixit, fantasy, cozy",
        "A firefly glowing in a field of poppies, Dixit, nature, whimsical",
        "A candle with a flame that turns into a ribbon, Dixit, artistic, surreal",
        "A bonfire with flames forming animal shapes, Dixit, playful, night",
        "A dragon sleeping on a bed of embers, Dixit, mythical, warm",
        "A fireplace with flames forming letters, Dixit, poetic, artistic",
        "A lantern with a flame that turns into a sun, Dixit, bright, magical",
        "A tree with leaves made of fire, Dixit, autumn, surreal",
        "A fox running through a field of glowing coals, Dixit, dynamic, animal",
        "A candle with a flame that turns into a butterfly, Dixit, transformation, dreamy",
        "A river of fire flowing through a snowy landscape, Dixit, contrast, fantasy",
        "A firefly glowing in a jar of swirling smoke, Dixit, dreamy, insect",
        "A fireplace with flames forming a dragon, Dixit, mythical, home"
    ],
    "flora": [
        "A giant sunflower with petals made of glass, Dixit, surreal, vibrant",
        "A tree with branches forming a spiral staircase, Dixit, dreamy, architecture",
        "A magical garden with floating lily pads, Dixit, fantasy, water",
        "A surreal forest with glowing mushrooms, Dixit, night, nature",
        "A vine wrapping around a floating lantern, Dixit, whimsical, light",
        "A treehouse hidden in a blooming cherry tree, Dixit, spring, fantasy",
        "A rose with petals turning into butterflies, Dixit, transformation, artistic",
        "A field of flowers with stems made of ribbons, Dixit, playful, colorful",
        "A plant growing from a teacup, Dixit, cozy, whimsical",
        "A garden with flowers blooming under the moon, Dixit, night, dreamy",
        "A tree with roots forming a river, Dixit, surreal, nature",
        "A sunflower with a face smiling at the sky, Dixit, cheerful, surreal",
        "A magical forest with trees made of crystal, Dixit, fantasy, sparkling",
        "A vine climbing a spiral tower, Dixit, architectural, whimsical",
        "A treehouse in a tree with rainbow leaves, Dixit, artistic, fantasy",
        "A rose with petals turning into musical notes, Dixit, creative, dreamy",
        "A garden with flowers blooming in the starlight, Dixit, night, magical",
        "A surreal landscape with trees made of feathers, Dixit, soft, fantasy",
        "A vine wrapping around a castle tower, Dixit, dreamy, architecture",
        "A tree with branches forming a heart, Dixit, love, surreal",
        "A sunflower with petals turning into stars, Dixit, cosmic, whimsical",
        "A field of flowers with petals made of mirrors, Dixit, reflective, surreal",
        "A plant growing from a book, Dixit, knowledge, whimsical",
        "A rose with petals turning into ribbons, Dixit, artistic, surreal",
        "A tree with branches forming a spiral, Dixit, dreamy, nature",
        "A garden with flowers blooming in the rain, Dixit, weather, magical",
        "A magical forest with glowing vines, Dixit, night, fantasy",
        "A vine wrapping around a floating island, Dixit, imaginative, surreal",
        "A treehouse in a tree with glowing fruit, Dixit, fantasy, night",
        "A sunflower with petals turning into clouds, Dixit, dreamy, sky"
    ],
    "food": [
        "A floating island made of chocolate and strawberries, Dixit, sweet, surreal",
        "A giant orange with a door and windows, Dixit, whimsical, fruit",
        "A surreal picnic with levitating teacups, Dixit, fantasy, afternoon",
        "A teapot pouring a river of honey, Dixit, artistic, golden",
        "A pizza with toppings turning into tiny animals, Dixit, playful, food",
        "A stack of pancakes with syrup waterfalls, Dixit, breakfast, fantasy",
        "A bowl of fruit with faces smiling, Dixit, cheerful, surreal",
        "A loaf of bread floating in a sea of milk, Dixit, dreamy, food",
        "A surreal landscape with candy canes as trees, Dixit, fantasy, sweet",
        "A cup of coffee with swirling galaxies, Dixit, cosmic, whimsical",
        "A plate of spaghetti forming a spiral staircase, Dixit, creative, food",
        "A cake with candles turning into butterflies, Dixit, transformation, celebration",
        "A picnic blanket floating among the clouds, Dixit, dreamy, food",
        "A teacup with a tiny boat sailing in tea, Dixit, adventure, whimsical",
        "A pizza with slices turning into birds, Dixit, surreal, food",
        "A stack of pancakes with syrup rivers, Dixit, artistic, breakfast",
        "A bowl of fruit with stems made of ribbons, Dixit, colorful, surreal",
        "A loaf of bread with a door and windows, Dixit, cozy, whimsical",
        "A surreal landscape with candy mountains, Dixit, fantasy, sweet",
        "A cup of coffee with a rainbow, Dixit, magical, morning",
        "A plate of spaghetti forming a musical staff, Dixit, creative, food",
        "A cake with candles turning into stars, Dixit, dreamy, celebration",
        "A picnic with floating sandwiches, Dixit, playful, food",
        "A teacup with a flower blooming inside, Dixit, botanical, artistic",
        "A pizza with toppings turning into stars, Dixit, cosmic, food",
        "A stack of pancakes with syrup waterfalls, Dixit, whimsical, breakfast",
        "A bowl of fruit with petals made of glass, Dixit, artistic, surreal",
        "A loaf of bread floating in a sky of clouds, Dixit, dreamy, food",
        "A surreal landscape with rivers of chocolate, Dixit, fantasy, sweet",
        "A cup of coffee with a sun rising from it, Dixit, morning, whimsical"
    ],
    "money": [
        "A tree with golden coins as leaves, Dixit, surreal, wealth",
        "A river of silver flowing through a fantasy city, Dixit, dreamy, money",
        "A piggy bank floating among clouds, Dixit, whimsical, savings",
        "A wallet opening to reveal a tiny magical world, Dixit, fantasy, treasure",
        "A stack of coins turning into butterflies, Dixit, transformation, whimsical",
        "A treasure chest with glowing emeralds, Dixit, fantasy, riches",
        "A golden key unlocking a door of coins, Dixit, surreal, opportunity",
        "A coin spinning in a pool of stars, Dixit, cosmic, money",
        "A landscape with floating bills as trees, Dixit, imaginative, surreal",
        "A piggy bank with wings, Dixit, playful, savings",
        "A wallet with a river of money flowing out, Dixit, abundance, whimsical",
        "A stack of coins forming a spiral staircase, Dixit, creative, money",
        "A treasure chest with a rainbow inside, Dixit, magical, riches",
        "A golden key opening a door to a magical vault, Dixit, fantasy, opportunity",
        "A coin spinning in a pool of gold, Dixit, dreamy, money",
        "A landscape with floating coins, Dixit, surreal, wealth",
        "A piggy bank with a door and windows, Dixit, cozy, savings",
        "A wallet with a garden blooming from it, Dixit, abundance, whimsical",
        "A stack of coins turning into stars, Dixit, cosmic, money",
        "A treasure chest with glowing coins, Dixit, magical, riches",
        "A golden key unlocking a treasure chest, Dixit, fantasy, opportunity",
        "A coin spinning in a pool of light, Dixit, radiant, money",
        "A landscape with floating treasure chests, Dixit, dreamy, riches",
        "A piggy bank with a rainbow, Dixit, cheerful, savings",
        "A wallet with a river of gold flowing out, Dixit, abundance, whimsical",
        "A stack of coins forming a spiral, Dixit, creative, money",
        "A treasure chest with a garden blooming inside, Dixit, magical, riches",
        "A golden key opening a door to a treasure room, Dixit, fantasy, opportunity",
        "A coin spinning in a pool of butterflies, Dixit, transformation, money",
        "A landscape with floating wallets, Dixit, surreal, savings"
    ],
    "sky" : [
    "A sky full of swirling pastel clouds, Dixit, dreamy, surreal",
    "A golden sun rising above a sea of fluffy clouds, Dixit, fantasy, vibrant",
    "A night sky with glowing constellations and floating clouds, Dixit, magical, artistic",
    "A rainbow arching across a sky of cotton candy clouds, Dixit, whimsical, vivid colors",
    "A flock of birds flying through a sky painted with auroras, Dixit, surreal, colorful",
    "A crescent moon resting on a bed of clouds, Dixit, poetic, dreamy",
    "A sky where clouds form the shapes of animals, Dixit, playful, fantasy",
    "A thunderstorm with lightning illuminating purple clouds, Dixit, dramatic, surreal",
    "A sky filled with floating islands among the clouds, Dixit, fantasy, imaginative",
    "A sunset sky with clouds turning into ribbons, Dixit, artistic, warm colors",
    "A sky with clouds shaped like musical notes, Dixit, whimsical, creative",
    "A starry sky with clouds reflecting the galaxy, Dixit, cosmic, dreamy",
    "A sky where clouds are made of books, Dixit, surreal, imaginative",
    "A sky with a staircase of clouds leading to the stars, Dixit, magical, fantasy",
    "A sky full of balloons floating among the clouds, Dixit, playful, colorful",
    "A sky with clouds shaped like clocks, time melting, Dixit, surreal, Dali",
    "A sky where clouds rain tiny stars, Dixit, magical, poetic",
    "A sky with clouds forming a giant face, Dixit, mysterious, surreal",
    "A sky where clouds are mirrors reflecting dreams, Dixit, artistic, dreamy",
    "A sky with clouds shaped like castles, Dixit, fantasy, imaginative",
    "A sky where clouds are made of flowers, Dixit, whimsical, colorful",
    "A sky with clouds forming a spiral, Dixit, surreal, artistic",
    "A sky where clouds are glowing lanterns, Dixit, magical, night",
    "A sky with clouds shaped like dragons, Dixit, fantasy, mythical",
    "A sky where clouds are floating origami, Dixit, creative, playful",
    "A sky with clouds forming a bridge to the moon, Dixit, dreamy, poetic",
    "A sky where clouds are made of butterflies, Dixit, whimsical, colorful",
    "A sky with clouds shaped like musical instruments, Dixit, artistic, surreal",
    "A sky where clouds are swirling like a vortex, Dixit, dramatic, fantasy",
    "A sky with clouds forming a giant heart, Dixit, romantic, dreamy"
],

    "sunny": [
        "A giant sun smiling over a surreal landscape, Dixit, Dali, surreal",
        "A sunflower field under a radiant sun, Dixit, Magritte, dreamy",
        "A child flying with sun-shaped balloons, Dixit, Carrington, fantasy",
        "A fox basking in golden sunlight, Dixit, Dali, artistic",
        "A tree with sun-shaped leaves, Dixit, Magritte, whimsical",
        "A river reflecting a glowing sun, Dixit, Carrington, fantasy",
        "A castle bathed in sunlight, Dixit, Dali, dreamy",
        "A sun rising over a field of flowers, Dixit, Magritte, artistic",
        "A bird soaring towards a radiant sun, Dixit, Carrington, fantasy",
        "A garden blooming under a golden sun, Dixit, Dali, whimsical",
        "A mountain with a sun-shaped peak, Dixit, Magritte, dreamy",
        "A fox chasing sunbeams, Dixit, Carrington, artistic",
        "A tree with branches reaching for the sun, Dixit, Dali, fantasy",
        "A river of sunlight flowing through a surreal landscape, Dixit, Magritte, whimsical",
        "A castle with sun-shaped windows, Dixit, Carrington, dreamy",
        "A child painting a sun in the sky, Dixit, Dali, artistic",
        "A sunflower with a face smiling at the sun, Dixit, Magritte, fantasy",
        "A bird singing to the rising sun, Dixit, Carrington, whimsical",
        "A garden with flowers turning towards the sun, Dixit, Dali, dreamy",
        "A mountain glowing in the sunlight, Dixit, Magritte, artistic",
        "A fox sleeping in a patch of sunlight, Dixit, Carrington, fantasy",
        "A tree with sun-shaped fruit, Dixit, Dali, whimsical",
        "A river reflecting a golden sun, Dixit, Magritte, dreamy",
        "A castle with a sun-shaped door, Dixit, Carrington, artistic",
        "A child holding a sun-shaped balloon, Dixit, Dali, fantasy",
        "A sunflower field glowing in the sunlight, Dixit, Magritte, whimsical",
        "A bird flying towards a radiant sun, Dixit, Carrington, dreamy",
        "A garden blooming under a smiling sun, Dixit, Dali, artistic",
        "A mountain with a sun-shaped shadow, Dixit, Magritte, fantasy",
        "A fox basking in the golden sunlight, Dixit, Carrington, whimsical"
    ],
    "tree": [
        "A giant tree with a door at its base, Dixit, Dali, surreal",
        "A tree with branches forming a spiral staircase, Dixit, Magritte, dreamy",
        "A treehouse nestled in a blooming tree, Dixit, Carrington, fantasy",
        "A tree with leaves made of butterflies, Dixit, Dali, artistic",
        "A tree growing on a floating island, Dixit, Magritte, whimsical",
        "A tree with roots forming a river, Dixit, Carrington, fantasy",
        "A tree with a swing hanging from a rainbow branch, Dixit, Dali, dreamy",
        "A tree with branches reaching for the stars, Dixit, Magritte, artistic",
        "A tree with a spiral trunk, Dixit, Carrington, fantasy",
        "A tree with glowing leaves, Dixit, Dali, whimsical",
        "A tree with a face smiling at the moon, Dixit, Magritte, dreamy",
        "A tree with branches forming a heart, Dixit, Carrington, artistic",
        "A tree with a door leading to another world, Dixit, Dali, fantasy",
        "A tree with roots wrapping around a castle, Dixit, Magritte, whimsical",
        "A tree with branches forming a bridge, Dixit, Carrington, dreamy",
        "A tree with leaves turning into birds, Dixit, Dali, artistic",
        "A tree with a swing hanging from a cloud, Dixit, Magritte, fantasy",
        "A tree with a spiral staircase in its trunk, Dixit, Carrington, whimsical",
        "A tree with glowing fruit, Dixit, Dali, dreamy",
        "A tree with branches forming a crown, Dixit, Magritte, artistic",
        "A tree with a door at its base, Dixit, Carrington, fantasy",
        "A tree with roots forming a spiral, Dixit, Dali, whimsical",
        "A tree with branches reaching for the sun, Dixit, Magritte, dreamy",
        "A tree with a face smiling at the stars, Dixit, Carrington, artistic",
        "A tree with leaves turning into ribbons, Dixit, Dali, fantasy",
        "A tree with a swing hanging from a rainbow, Dixit, Magritte, whimsical",
        "A tree with branches forming a spiral, Dixit, Carrington, dreamy",
        "A tree with glowing leaves, Dixit, Dali, artistic",
        "A tree with a door leading to a magical world, Dixit, Magritte, fantasy",
        "A tree with roots wrapping around a floating island, Dixit, Carrington, whimsical"
    ],
    "watch": [
        "A melting watch draped over a tree branch, Dixit, Dali, surreal",
        "A pocket watch floating in a surreal sky, Dixit, Magritte, dreamy",
        "A clock tower with swirling clouds, Dixit, Carrington, fantasy",
        "A watch with hands turning into butterflies, Dixit, Dali, artistic",
        "A clock face with numbers floating away, Dixit, Magritte, whimsical",
        "A watch with a miniature city inside, Dixit, Carrington, fantasy",
        "A clock with gears turning into flowers, Dixit, Dali, dreamy",
        "A watch with a river of time flowing out, Dixit, Magritte, artistic",
        "A clock tower with a spiral staircase, Dixit, Carrington, fantasy",
        "A watch with a face smiling at the moon, Dixit, Dali, whimsical",
        "A clock with hands turning into ribbons, Dixit, Magritte, dreamy",
        "A watch with a garden blooming inside, Dixit, Carrington, artistic",
        "A clock with numbers turning into stars, Dixit, Dali, fantasy",
        "A watch with a river of time flowing through a surreal landscape, Dixit, Magritte, whimsical",
        "A clock tower with a door leading to another world, Dixit, Carrington, dreamy",
        "A watch with hands turning into birds, Dixit, Dali, artistic",
        "A clock with gears turning into ribbons, Dixit, Magritte, fantasy",
        "A watch with a miniature forest inside, Dixit, Carrington, whimsical",
        "A clock with numbers floating in the sky, Dixit, Dali, dreamy",
        "A watch with a face smiling at the stars, Dixit, Magritte, artistic",
        "A clock with hands turning into clouds, Dixit, Carrington, fantasy",
        "A watch with a river of time flowing into a garden, Dixit, Dali, whimsical",
        "A clock tower with a spiral staircase, Dixit, Magritte, dreamy",
        "A watch with a garden blooming from its center, Dixit, Carrington, artistic",
        "A clock with numbers turning into ribbons, Dixit, Dali, fantasy",
        "A watch with hands turning into stars, Dixit, Magritte, whimsical",
        "A clock with gears turning into clouds, Dixit, Carrington, dreamy",
        "A watch with a miniature city inside, Dixit, Dali, artistic",
        "A clock with numbers floating away, Dixit, Magritte, fantasy",
        "A watch with a river of time flowing through a magical world, Dixit, Carrington, whimsical"
    ],
    "winter": [
        "A snow-covered tree glowing under the northern lights, Dixit, Dali, surreal",
        "A fox curled up in a snowy landscape, Dixit, Magritte, dreamy",
        "A castle made of ice and snow, Dixit, Carrington, fantasy",
        "A snowman with a glowing lantern, Dixit, Dali, artistic",
        "A river frozen in time, Dixit, Magritte, whimsical",
        "A child sledding down a hill of clouds, Dixit, Carrington, fantasy",
        "A bear sleeping in a snowy cave, Dixit, Dali, dreamy",
        "A snowflake turning into a butterfly, Dixit, Magritte, artistic",
        "A tree with branches made of icicles, Dixit, Carrington, fantasy",
        "A fox chasing snowflakes, Dixit, Dali, whimsical",
        "A castle with icicles hanging from the towers, Dixit, Magritte, dreamy",
        "A snowman with a scarf made of stars, Dixit, Carrington, artistic",
        "A river of ice flowing through a surreal landscape, Dixit, Dali, fantasy",
        "A child building a snow fort with glowing walls, Dixit, Magritte, whimsical",
        "A bear skating on a frozen pond, Dixit, Carrington, dreamy",
        "A snowflake turning into a ribbon, Dixit, Dali, artistic",
        "A tree with branches covered in snow, Dixit, Magritte, fantasy",
        "A fox sleeping in a snowy field, Dixit, Carrington, whimsical",
        "A castle made of snow and ice, Dixit, Dali, dreamy",
        "A snowman with a hat made of clouds, Dixit, Magritte, artistic",
        "A river frozen in a spiral, Dixit, Carrington, fantasy",
        "A child sledding down a hill of stars, Dixit, Dali, whimsical",
        "A bear sleeping under a snowy tree, Dixit, Magritte, dreamy",
        "A snowflake turning into a star, Dixit, Carrington, artistic",
        "A tree with branches made of snowflakes, Dixit, Dali, fantasy",
        "A fox chasing a snowflake, Dixit, Magritte, whimsical",
        "A castle with towers made of ice, Dixit, Carrington, dreamy",
        "A snowman with a scarf made of ribbons, Dixit, Dali, artistic",
        "A river of ice flowing through a magical world, Dixit, Magritte, fantasy",
        "A child building a snow fort with glowing snow, Dixit, Carrington, whimsical"
    ]
}

#